"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const LectureController_1 = __importDefault(require("../http/controllers/LectureController"));
const isAuthenticated_1 = require("../middlewares/isAuthenticated");
const express_1 = require("express");
const lecturesRouter = (0, express_1.Router)();
const lectureController = new LectureController_1.default();
lecturesRouter.use(isAuthenticated_1.checkIsAuthenticated);
lecturesRouter.get('/lectures/:lectureId', lectureController.get);
lecturesRouter.patch('/lectures/:lectureId/update', lectureController.updateLecture);
lecturesRouter.delete('/lectures/:lectureId/delete', lectureController.deleteLecture);
lecturesRouter.get('/lectures/:lectureId/links', lectureController.getLinks);
lecturesRouter.post('/lectures/:lectureId/links/create', lectureController.createLink);
lecturesRouter.get('/lectures/links/:linkId', lectureController.getLink);
lecturesRouter.patch('/lectures/links/:linkId/update', lectureController.updateLink);
lecturesRouter.delete('/lectures/links/:linkId/delete', lectureController.deleteLink);
exports.default = lecturesRouter;
