"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const SubjectController_1 = __importDefault(require("../http/controllers/SubjectController"));
const isAuthenticated_1 = require("../middlewares/isAuthenticated");
const express_1 = require("express");
const subjectRouter = (0, express_1.Router)();
const controller = new SubjectController_1.default();
subjectRouter.use(isAuthenticated_1.checkIsAuthenticated);
subjectRouter.get('/subjects/:moduleId', controller.get);
subjectRouter.post('/subjects/:moduleId/create', controller.createSubject);
subjectRouter.get('/subjects/:moduleId/:subjectId', controller.getSubject);
subjectRouter.patch('/subjects/:moduleId/:subjectId/update', controller.updateSubject);
subjectRouter.delete('/subjects/:moduleId/:subjectId/delete', controller.deleteSubject);
subjectRouter.get('/subjects/:moduleId/:subjectId/lectures', controller.getSubjectLectures);
subjectRouter.get('/subjects/:moduleId/:subjectId/final-revisions', controller.getSubjectFinalRevisions);
subjectRouter.get('/subjects/:moduleId/:subjectId/practical', controller.getSubjectPractical);
subjectRouter.post('/subjects/:moduleId/:subjectId/create/lecture', controller.createLecture);
subjectRouter.post('/subjects/:moduleId/:subjectId/create/practical', controller.createPractical);
subjectRouter.post('/subjects/:moduleId/:subjectId/create/final-revision', controller.createFinalRevision);
subjectRouter.patch('/subjects/:moduleId/:subjectId/create/lecture/:lectureId/update', controller.updateLecture);
subjectRouter.patch('/subjects/:moduleId/:subjectId/create/practical/:practicalId/update', controller.updatePractical);
subjectRouter.patch('/subjects/:moduleId/:subjectId/create/final-revision/:finalId/update', controller.updateFinalRevision);
exports.default = subjectRouter;
